-- GATE 15 · Zero-mutation PRE snapshot (READ ONLY) — repetir idéntico al cierre
SELECT jsonb_build_object(
  'ts', now(),
  'products_all',        (SELECT count(*) FROM products),
  'products_store',      (SELECT count(*) FROM products WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'products_store_stock',(SELECT COALESCE(SUM(stock_current),0) FROM products WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'products_store_cost', (SELECT COALESCE(SUM(cost_average),0) FROM products WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'inventory_all',       (SELECT count(*) FROM inventory),
  'inventory_store',     (SELECT count(*) FROM inventory WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'inventory_sum',       (SELECT COALESCE(SUM(quantity),0) FROM inventory),
  'stock_movements_all', (SELECT count(*) FROM stock_movements),
  'stock_movements_store',(SELECT count(*) FROM stock_movements WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'stock_movements_sum', (SELECT COALESCE(SUM(quantity_change),0) FROM stock_movements),
  'kardex_all',          (SELECT count(*) FROM kardex_entries),
  'kardex_store',        (SELECT count(*) FROM kardex_entries WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'transactions_all',    (SELECT count(*) FROM transactions),
  'transactions_store',  (SELECT count(*) FROM transactions WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'transaction_items_all',(SELECT count(*) FROM transaction_items),
  'devolutions_all',     (SELECT count(*) FROM devolutions),
  'devolutions_store',   (SELECT count(*) FROM devolutions WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'devolution_items_all',(SELECT count(*) FROM devolution_items),
  'payments_all',        (SELECT count(*) FROM payment_transactions),
  'payments_store_tx',   (SELECT count(*) FROM payment_transactions pt JOIN transactions t ON t.id=pt.transaction_id WHERE t.store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'receipts_all',        (SELECT count(*) FROM receipts),
  'receipts_store',      (SELECT count(*) FROM receipts WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'transfers_all',       (SELECT count(*) FROM transfers),
  'transfers_store',     (SELECT count(*) FROM transfers WHERE origin_store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576' OR destination_store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'audit_logs_all',      (SELECT count(*) FROM audit_logs),
  'audit_logs_store',    (SELECT count(*) FROM audit_logs WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'restore_sessions_all',(SELECT count(*) FROM restore_sessions),
  'store_reset_snapshots_all',(SELECT count(*) FROM store_reset_snapshots),
  'commissions_all',     (SELECT count(*) FROM commission_payments),
  'wac_log_all',         (SELECT count(*) FROM wac_change_log),
  'wac_log_store',       (SELECT count(*) FROM wac_change_log WHERE store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'products_checksum',   (SELECT md5(string_agg(p.id::text || '|' || p.stock_current::text || '|' || COALESCE(p.cost_average::text,'') || '|' || p.updated_at::text, ',' ORDER BY p.id))
                           FROM products p WHERE p.store_id='d1c4ba0e-5767-4ba0-e576-7d1c4ba0e576'),
  'inventory_checksum',  (SELECT md5(string_agg(i.id::text || '|' || i.quantity::text, ',' ORDER BY i.id)) FROM inventory i),
  'movements_checksum',  (SELECT md5(string_agg(m.id::text || '|' || m.quantity_change::text, ',' ORDER BY m.id)) FROM stock_movements m)
) AS evidence;
