services:
  - type: web
    name: Costpro
    runtime: bun
    buildCommand: bun install && bun x prisma generate && bun run build
    startCommand: bun .next/standalone/server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: 'postgresql://dummy:dummy@localhost:5432/dummy'
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
