import re

with open('src/lib/export/pdf-generator.ts', 'r') as f:
    content = f.read()

# Update Footer logic to be format-aware
footer_new = r"""    // Footer
    if (showDateTime) {
      doc.setFontSize(7);
      doc.setTextColor(150);
      doc.setFont('helvetica', 'normal');
      const ts = new Date().toLocaleString('es-CU');
      const dateOnly = new Date().toLocaleDateString('es-CU');

      let footerText = `${ts} | Pág. ${i}/${pageCount} | CostPro`;
      if (pdfFormat === 'bilingue') {
          footerText = `${ts} | Pág. ${i}/${pageCount} | CostPro Export / Exportación CostPro`;
      } else if (pdfFormat === 'exportacion') {
          footerText = `${ts} | Pág. ${i}/${pageCount} | Generado por CostPro / Generated by CostPro`;
      } else if (pdfFormat === 'res148') {
          footerText = `Conforme Res. 148/2023 | Fecha: ${dateOnly} | Pág. ${i}/${pageCount}`;
      }

      doc.text(footerText, pageWidth / 2, pageHeight - 6, { align: 'center' });
    }"""

# Escaping single quotes for the regex
pattern = r'// Footer.*?doc\.text\(footerText, pageWidth / 2, pageHeight - 6, \{ align: \'center\' \}\);.*?\}'

# The regex approach seems brittle with the complex footerText variable,
# let's use a simpler string replace for the core footer logic

content = content.replace("""    // Footer
    if (showDateTime) {
      doc.setFontSize(7);
      doc.setTextColor(150);
      doc.setFont('helvetica', 'normal');
      const ts = new Date().toLocaleString('es-CU');
      doc.text(`${ts} | Pág. ${i}/${pageCount} | CostPro`, pageWidth / 2, pageHeight - 6, { align: 'center' });
    }""", footer_new)

# Add timestamp to Standard header
standard_header_ts = r"""    } else {
      d.setFontSize(16);
      d.setFont('helvetica', 'bold');
      d.setTextColor(...color);
      d.text(title, 14, 20);

      if (showDateTime) {
          const ts = new Date().toLocaleString('es-CU');
          d.setFontSize(8);
          d.setFont('helvetica', 'normal');
          d.setTextColor(100);
          d.text(ts, pageWidth - 14, 20, { align: 'right' });
      }

      d.setTextColor(0, 0, 0);
      return 30;
    }"""

content = content.replace("""    } else {
      d.setFontSize(16);
      d.setFont('helvetica', 'bold');
      d.setTextColor(...color);
      d.text(title, 14, 20);
      d.setTextColor(0, 0, 0);
      return 30;
    }""", standard_header_ts)

with open('src/lib/export/pdf-generator.ts', 'w') as f:
    f.write(content)
