import { describe, it, expect, vi, beforeEach } from 'vitest';
import { auditService } from '@/services/audit-service';
import { supabase } from '@/lib/supabaseClient';

vi.mock('@/lib/supabaseClient', () => ({
  supabase: {
    from: vi.fn(() => ({
      insert: vi.fn().mockResolvedValue({ error: null })
    }))
  }
}));

vi.mock('@/lib/supabase-admin', () => ({
  getAdminClient: vi.fn().mockResolvedValue({
    from: vi.fn(() => ({
      insert: vi.fn().mockResolvedValue({ error: null })
    }))
  })
}));

describe('auditService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('covers various logging methods', async () => {
    await auditService.logInvoiceWithoutPrice('u1', 'p1', 's1');
    await auditService.logSaleBelowCost('u1', 'p1', 's1', 10, 20);
    await auditService.logFCTemplateUpdated({
        userId: 'u1', storeId: 's1', templateId: 't1', modalidad: 'm1', isActive: true
    });
    await auditService.logFCGenerated({
        userId: 'u1', productId: 'p1', storeId: 's1', templateId: 't1', costPrice: 10, salePrice: 15, isAutoGenerated: false
    });
    await auditService.logFCPdfExported({
        userId: 'u1', productId: 'p1', storeId: 's1', pdfFormat: 'f1'
    });
    await auditService.logStockAdjustment({
        userId: 'u1', productId: 'p1', storeId: 's1', oldStock: 10, newStock: 20, reason: 'r'
    });
    await auditService.logPriceChange({
        userId: 'u1', productId: 'p1', storeId: 's1', oldPrice: 10, newPrice: 15
    });

    expect(supabase.from).toHaveBeenCalled();
  });
});
