'use client';

/**
 * @file BulkConfirmationFlow.tsx
 * @description Iteración 8 — Flujo de confirmación para bulk delete.
 *
 * Maneja:
 *   - Step 1: confirmation_text='BULK_DELETE' + reason (min 10 chars)
 *   - Step 2: Generar confirmation_token
 *   - Step 3 (si requiere override): Input para override_token o
 *            solicitar a otro admin que genere el override
 *   - Step 4: Execute
 *
 * Estados temporales:
 *   - No guarda tokens en localStorage
 *   - Si el componente se desmonta (refresh/cierre), los tokens se pierden
 *   - El usuario debe volver a hacer preview
 *
 * Seguridad:
 *   - confirmation_text debe ser exactamente 'BULK_DELETE'
 *   - reason mínimo 10 caracteres
 *   - confirmation_token se genera server-side
 *   - override_token requiere autenticación de OTRO admin
 */

import React, { useState } from 'react';
import { Loader2, Shield, AlertTriangle, KeyRound, UserCheck } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import {
  useGenerateBulkToken,
  useGenerateBulkOverride,
  useBulkExecute,
  type BulkPreviewResult,
} from '@/hooks/api/useStores';

interface BulkConfirmationFlowProps {
  preview: BulkPreviewResult;
  storeIds: string[];
  action: 'delete' | 'archive';
  onComplete: (result: { success: boolean; processed?: number; failed?: number }) => void;
  onCancel: () => void;
}

type Step = 'confirm' | 'token' | 'override' | 'executing' | 'done';

export function BulkConfirmationFlow({
  preview,
  storeIds,
  action,
  onComplete,
  onCancel,
}: BulkConfirmationFlowProps) {
  const [step, setStep] = useState<Step>('confirm');
  const [confirmationText, setConfirmationText] = useState('');
  const [reason, setReason] = useState('');
  const [confirmationToken, setConfirmationToken] = useState<string | null>(null);
  const [overrideToken, setOverrideToken] = useState<string>('');
  const [overrideReason, setOverrideReason] = useState('');

  const generateTokenMutation = useGenerateBulkToken();
  const generateOverrideMutation = useGenerateBulkOverride();
  const executeMutation = useBulkExecute();

  const requiresOverride = preview.requires_override;
  const expectedText = 'BULK_DELETE';

  // Step 1: Validate confirmation_text and reason
  const canProceedToToken =
    action !== 'delete' ||
    (confirmationText === expectedText && reason.length >= 10);

  // Step 2: Generate confirmation_token
  const handleGenerateToken = async () => {
    if (!canProceedToToken) {
      toast.error('Escribe BULK_DELETE y un motivo de mínimo 10 caracteres');
      return;
    }

    try {
      const result = await generateTokenMutation.mutateAsync({
        storeIds,
        action,
      });
      setConfirmationToken(result.confirmation_token);
      if (result.has_protected_stores && requiresOverride) {
        setStep('override');
      } else {
        setStep('executing');
        await handleExecute(result.confirmation_token, null);
      }
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : 'Error al generar token');
    }
  };

  // Step 3: Generate override_token (by another admin)
  const handleGenerateOverride = async () => {
    if (!confirmationToken) {
      toast.error('Falta confirmation_token');
      return;
    }

    if (overrideReason.length < 10) {
      toast.error('El motivo del override debe tener mínimo 10 caracteres');
      return;
    }

    try {
      const result = await generateOverrideMutation.mutateAsync({
        confirmation_token: confirmationToken,
        reason: overrideReason,
      });
      setOverrideToken(result.override_token);
      setStep('executing');
      await handleExecute(confirmationToken, result.override_token);
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : 'Error al generar override');
    }
  };

  // Step 3 alternative: Admin manually enters override_token generated by another admin
  const handleManualOverrideToken = async () => {
    if (!overrideToken || overrideToken.length < 10) {
      toast.error('Ingresa el override_token válido');
      return;
    }
    setStep('executing');
    await handleExecute(confirmationToken, overrideToken);
  };

  // Step 4: Execute
  const handleExecute = async (ct: string, ot: string | null) => {
    try {
      const result = await executeMutation.mutateAsync({
        storeIds,
        action,
        confirmation_text: action === 'delete' ? 'BULK_DELETE' : undefined,
        reason: reason || undefined,
        confirmation_token: ct,
        override_token: ot || undefined,
      });

      setStep('done');
      onComplete({
        success: result.success,
        processed: result.processed,
        failed: result.failed,
      });
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : 'Error en execute');
      setStep('confirm');
    }
  };

  const isLoading =
    generateTokenMutation.isPending ||
    generateOverrideMutation.isPending ||
    executeMutation.isPending;

  return (
    <div className="space-y-4">
      {/* Step indicator */}
      <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">
        <div className={cn('flex items-center gap-1', step === 'confirm' && 'text-foreground')}>
          <span className={cn('w-5 h-5 rounded-full flex items-center justify-center text-[10px]',
            step === 'confirm' ? 'bg-primary text-primary-foreground' : 'bg-muted')}>
            1
          </span>
          Confirmar
        </div>
        <div className="w-8 h-px bg-border" />
        <div className={cn('flex items-center gap-1',
          (step === 'token' || step === 'override' || step === 'executing' || step === 'done') && 'text-foreground')}>
          <span className={cn('w-5 h-5 rounded-full flex items-center justify-center text-[10px]',
            (step === 'token' || step === 'override' || step === 'executing' || step === 'done')
              ? 'bg-primary text-primary-foreground' : 'bg-muted')}>
            2
          </span>
          Token
        </div>
        {requiresOverride && (
          <>
            <div className="w-8 h-px bg-border" />
            <div className={cn('flex items-center gap-1',
              (step === 'override' || step === 'executing' || step === 'done') && 'text-foreground')}>
              <span className={cn('w-5 h-5 rounded-full flex items-center justify-center text-[10px]',
                (step === 'override' || step === 'executing' || step === 'done')
                  ? 'bg-primary text-primary-foreground' : 'bg-muted')}>
                3
              </span>
              Override
            </div>
          </>
        )}
        <div className="w-8 h-px bg-border" />
        <div className={cn('flex items-center gap-1',
          (step === 'executing' || step === 'done') && 'text-foreground')}>
          <span className={cn('w-5 h-5 rounded-full flex items-center justify-center text-[10px]',
            (step === 'executing' || step === 'done')
              ? 'bg-primary text-primary-foreground' : 'bg-muted')}>
            {requiresOverride ? '4' : '3'}
          </span>
          Execute
        </div>
      </div>

      {/* Step 1: Confirmation */}
      {step === 'confirm' && (
        <div className="space-y-4">
          {action === 'delete' && (
            <>
              <div className="p-3 rounded-lg border border-destructive/30 bg-destructive/5">
                <div className="flex items-center gap-2 text-destructive font-bold mb-1">
                  <AlertTriangle className="w-4 h-4" />
                  Operación destructiva
                </div>
                <div className="text-sm text-muted-foreground">
                  Vas a eliminar <strong>{storeIds.length}</strong> tienda(s).
                  Esta acción desactivará las tiendas, revocará memberships y limpiará
                  active_store_id. Los datos se conservan pero la operación es
                  irreversible en términos de acceso.
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="confirmation_text">
                  Escribe <code className="px-1 py-0.5 rounded bg-muted font-mono text-destructive">BULK_DELETE</code> para confirmar
                </Label>
                <Input
                  id="confirmation_text"
                  value={confirmationText}
                  onChange={(e) => setConfirmationText(e.target.value)}
                  placeholder="BULK_DELETE"
                  className={cn(
                    'font-mono',
                    confirmationText && confirmationText !== expectedText && 'border-destructive'
                  )}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="reason">
                  Motivo (mínimo 10 caracteres) <span className="text-destructive">*</span>
                </Label>
                <Textarea
                  id="reason"
                  value={reason}
                  onChange={(e) => setReason(e.target.value)}
                  placeholder="Ej: Cierre de locales por reestructuración comercial..."
                  rows={3}
                  className={cn(
                    reason && reason.length < 10 && 'border-warning'
                  )}
                />
                <div className={cn('text-xs', reason.length < 10 ? 'text-warning' : 'text-muted-foreground')}>
                  {reason.length}/10 caracteres mínimos
                </div>
              </div>
            </>
          )}

          {action === 'archive' && (
            <div className="p-3 rounded-lg border border-warning/30 bg-warning/5">
              <div className="flex items-center gap-2 text-warning font-bold mb-1">
                <AlertTriangle className="w-4 h-4" />
                Archivado
              </div>
              <div className="text-sm text-muted-foreground">
                Vas a archivar <strong>{storeIds.length}</strong> tienda(s).
                Las tiendas se desactivarán pero todos los datos se conservan.
              </div>
            </div>
          )}

          <div className="flex justify-between gap-2">
            <Button variant="outline" onClick={onCancel} disabled={isLoading}>
              Cancelar
            </Button>
            <Button
              onClick={handleGenerateToken}
              disabled={!canProceedToToken || isLoading}
              variant={action === 'delete' ? 'destructive' : 'default'}
            >
              {isLoading ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <KeyRound className="w-4 h-4 mr-2" />
              )}
              Generar token de confirmación
            </Button>
          </div>
        </div>
      )}

      {/* Step 2: Token generated (only shown briefly for non-override flow) */}
      {step === 'token' && (
        <div className="space-y-4">
          <div className="p-3 rounded-lg border border-success/30 bg-success/5">
            <div className="flex items-center gap-2 text-success font-bold mb-1">
              <KeyRound className="w-4 h-4" />
              Token generado
            </div>
            <div className="text-sm text-muted-foreground">
              confirmation_token generado. Procediendo con execute...
            </div>
          </div>
        </div>
      )}

      {/* Step 3: Override (for protected stores) */}
      {step === 'override' && (
        <div className="space-y-4">
          <div className="p-3 rounded-lg border border-warning/30 bg-warning/5">
            <div className="flex items-center gap-2 text-warning font-bold mb-2">
              <Shield className="w-4 h-4" />
              Doble confirmación requerida
            </div>
            <div className="text-sm text-muted-foreground mb-3">
              Hay <strong>{preview.protected_stores.length}</strong> tienda(s) protegida(s).
              Se requiere que <strong>otro administrador</strong> genere un override_token.
            </div>
            <div className="text-xs text-muted-foreground bg-muted/50 p-2 rounded">
              El admin que inicia la operación NO puede generar el override.
              Debes pedir a otro admin que:
              <ol className="list-decimal ml-4 mt-1 space-y-0.5">
                <li>Inicie sesión con sus credenciales</li>
                <li>Use el endpoint <code>/api/stores/bulk/generate-override</code></li>
                <li>Te comparta el override_token generado</li>
              </ol>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="override_token">Override token (generado por otro admin)</Label>
            <Input
              id="override_token"
              value={overrideToken}
              onChange={(e) => setOverrideToken(e.target.value)}
              placeholder="bot_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
              className="font-mono text-sm"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="override_reason">
              Motivo del override (mínimo 10 caracteres)
            </Label>
            <Textarea
              id="override_reason"
              value={overrideReason}
              onChange={(e) => setOverrideReason(e.target.value)}
              placeholder="Ej: Autorizo la eliminación tras verificar que los locales cerraron..."
              rows={2}
            />
          </div>

          <div className="flex justify-between gap-2">
            <Button variant="outline" onClick={onCancel} disabled={isLoading}>
              Cancelar
            </Button>
            <Button
              onClick={handleManualOverrideToken}
              disabled={!overrideToken || overrideToken.length < 10 || isLoading}
              variant="destructive"
            >
              {isLoading ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <UserCheck className="w-4 h-4 mr-2" />
              )}
              Ejecutar eliminación
            </Button>
          </div>
        </div>
      )}

      {/* Step 4: Executing */}
      {step === 'executing' && (
        <div className="flex items-center justify-center py-8">
          <div className="text-center">
            <Loader2 className="w-8 h-8 animate-spin mx-auto mb-3 text-primary" />
            <div className="font-bold text-foreground">Ejecutando operación...</div>
            <div className="text-sm text-muted-foreground mt-1">
              No cierres esta ventana. La operación es atómica.
            </div>
          </div>
        </div>
      )}

      {/* Step 5: Done */}
      {step === 'done' && (
        <div className="flex items-center justify-center py-8">
          <div className="text-center">
            <div className="text-2xl mb-2">✓</div>
            <div className="font-bold text-foreground">Operación completada</div>
          </div>
        </div>
      )}
    </div>
  );
}
