export const COLUMN_LABELS: Record<string, string> = {
  id: 'ID',
  created_at: 'Fecha',
  total_amount: 'Monto Total',
  status: 'Estado',
  payment_method: 'Método de Pago',
  subtotal: 'Subtotal',
  discount_value: 'Descuento',
  name: 'Nombre',
  sku: 'SKU',
  stock_current: 'Stock Actual',
  price: 'Precio',
  cost_price: 'Precio Costo',
  action: 'Acción',
  table_name: 'Tabla',
  store_name: 'Tienda',
  profile: 'Perfil',
  movement_type: 'Tipo Mov.',
  quantity_change: 'Cant. Cambio',
  balance_after: 'Saldo Posterior',
  unit_cost: 'Costo Unit.',
  supplier: 'Proveedor',
  total_cost: 'Costo Total',
  reference_doc: 'Doc. Referencia',
  notes: 'Notas',
  profit: 'Utilidad',
  margin_percentage: '% Margen',
  date: 'Fecha',
  total_income: 'Total Ingresos',
  total_expenses: 'Total Gastos/Costos',
  origin_store_name: 'Origen',
  destination_store_name: 'Destino',
  creator_name: 'Creado por',
  declared_cash: 'Efectivo Decl.',
  declared_vouchers: 'Vales/Transf.',
  system_total: 'Total Sist.',
  difference: 'Diferencia',
  operator_name: 'Operador',
  closed_at: 'Cierre'
};
